# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yezhou/tls/extern/cmake/bin/cmake

# The command to remove a file.
RM = /home/yezhou/tls/extern/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yezhou/tls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yezhou/tls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	extern/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	extern/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	extern/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	extern/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	extern/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	extern/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	extern/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yezhou/tls/CMakeFiles /home/yezhou/tls/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yezhou/tls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/CMakeFiles/uninstall.dir/build.make extern/libressl/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/crypto/CMakeFiles/crypto.dir/build.make extern/libressl/crypto/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named ssl

# Build rule for target.
ssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssl
.PHONY : ssl

# fast build rule for target.
ssl/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/ssl/CMakeFiles/ssl.dir/build.make extern/libressl/ssl/CMakeFiles/ssl.dir/build
.PHONY : ssl/fast

#=============================================================================
# Target rules for targets named ocspcheck

# Build rule for target.
ocspcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ocspcheck
.PHONY : ocspcheck

# fast build rule for target.
ocspcheck/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/apps/ocspcheck/CMakeFiles/ocspcheck.dir/build.make extern/libressl/apps/ocspcheck/CMakeFiles/ocspcheck.dir/build
.PHONY : ocspcheck/fast

#=============================================================================
# Target rules for targets named openssl

# Build rule for target.
openssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openssl
.PHONY : openssl

# fast build rule for target.
openssl/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/apps/openssl/CMakeFiles/openssl.dir/build.make extern/libressl/apps/openssl/CMakeFiles/openssl.dir/build
.PHONY : openssl/fast

#=============================================================================
# Target rules for targets named nc

# Build rule for target.
nc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nc
.PHONY : nc

# fast build rule for target.
nc/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/apps/nc/CMakeFiles/nc.dir/build.make extern/libressl/apps/nc/CMakeFiles/nc.dir/build
.PHONY : nc/fast

#=============================================================================
# Target rules for targets named tls

# Build rule for target.
tls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tls
.PHONY : tls

# fast build rule for target.
tls/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tls/CMakeFiles/tls.dir/build.make extern/libressl/tls/CMakeFiles/tls.dir/build
.PHONY : tls/fast

#=============================================================================
# Target rules for targets named x509name

# Build rule for target.
x509name: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 x509name
.PHONY : x509name

# fast build rule for target.
x509name/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/x509name.dir/build.make extern/libressl/tests/CMakeFiles/x509name.dir/build
.PHONY : x509name/fast

#=============================================================================
# Target rules for targets named x25519test

# Build rule for target.
x25519test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 x25519test
.PHONY : x25519test

# fast build rule for target.
x25519test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/x25519test.dir/build.make extern/libressl/tests/CMakeFiles/x25519test.dir/build
.PHONY : x25519test/fast

#=============================================================================
# Target rules for targets named tls_prf

# Build rule for target.
tls_prf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tls_prf
.PHONY : tls_prf

# fast build rule for target.
tls_prf/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/tls_prf.dir/build.make extern/libressl/tests/CMakeFiles/tls_prf.dir/build
.PHONY : tls_prf/fast

#=============================================================================
# Target rules for targets named tls_ext_alpn

# Build rule for target.
tls_ext_alpn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tls_ext_alpn
.PHONY : tls_ext_alpn

# fast build rule for target.
tls_ext_alpn/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/tls_ext_alpn.dir/build.make extern/libressl/tests/CMakeFiles/tls_ext_alpn.dir/build
.PHONY : tls_ext_alpn/fast

#=============================================================================
# Target rules for targets named ssl_versions

# Build rule for target.
ssl_versions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssl_versions
.PHONY : ssl_versions

# fast build rule for target.
ssl_versions/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/ssl_versions.dir/build.make extern/libressl/tests/CMakeFiles/ssl_versions.dir/build
.PHONY : ssl_versions/fast

#=============================================================================
# Target rules for targets named sm4test

# Build rule for target.
sm4test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sm4test
.PHONY : sm4test

# fast build rule for target.
sm4test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/sm4test.dir/build.make extern/libressl/tests/CMakeFiles/sm4test.dir/build
.PHONY : sm4test/fast

#=============================================================================
# Target rules for targets named sm3test

# Build rule for target.
sm3test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sm3test
.PHONY : sm3test

# fast build rule for target.
sm3test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/sm3test.dir/build.make extern/libressl/tests/CMakeFiles/sm3test.dir/build
.PHONY : sm3test/fast

#=============================================================================
# Target rules for targets named sha512test

# Build rule for target.
sha512test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sha512test
.PHONY : sha512test

# fast build rule for target.
sha512test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/sha512test.dir/build.make extern/libressl/tests/CMakeFiles/sha512test.dir/build
.PHONY : sha512test/fast

#=============================================================================
# Target rules for targets named sha1test

# Build rule for target.
sha1test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sha1test
.PHONY : sha1test

# fast build rule for target.
sha1test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/sha1test.dir/build.make extern/libressl/tests/CMakeFiles/sha1test.dir/build
.PHONY : sha1test/fast

#=============================================================================
# Target rules for targets named rmdtest

# Build rule for target.
rmdtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rmdtest
.PHONY : rmdtest

# fast build rule for target.
rmdtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/rmdtest.dir/build.make extern/libressl/tests/CMakeFiles/rmdtest.dir/build
.PHONY : rmdtest/fast

#=============================================================================
# Target rules for targets named ssltest

# Build rule for target.
ssltest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssltest
.PHONY : ssltest

# fast build rule for target.
ssltest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/ssltest.dir/build.make extern/libressl/tests/CMakeFiles/ssltest.dir/build
.PHONY : ssltest/fast

#=============================================================================
# Target rules for targets named servertest

# Build rule for target.
servertest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 servertest
.PHONY : servertest

# fast build rule for target.
servertest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/servertest.dir/build.make extern/libressl/tests/CMakeFiles/servertest.dir/build
.PHONY : servertest/fast

#=============================================================================
# Target rules for targets named rfc5280time

# Build rule for target.
rfc5280time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rfc5280time
.PHONY : rfc5280time

# fast build rule for target.
rfc5280time/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/rfc5280time.dir/build.make extern/libressl/tests/CMakeFiles/rfc5280time.dir/build
.PHONY : rfc5280time/fast

#=============================================================================
# Target rules for targets named record_layer_test

# Build rule for target.
record_layer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 record_layer_test
.PHONY : record_layer_test

# fast build rule for target.
record_layer_test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/record_layer_test.dir/build.make extern/libressl/tests/CMakeFiles/record_layer_test.dir/build
.PHONY : record_layer_test/fast

#=============================================================================
# Target rules for targets named rc2test

# Build rule for target.
rc2test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rc2test
.PHONY : rc2test

# fast build rule for target.
rc2test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/rc2test.dir/build.make extern/libressl/tests/CMakeFiles/rc2test.dir/build
.PHONY : rc2test/fast

#=============================================================================
# Target rules for targets named poly1305test

# Build rule for target.
poly1305test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poly1305test
.PHONY : poly1305test

# fast build rule for target.
poly1305test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/poly1305test.dir/build.make extern/libressl/tests/CMakeFiles/poly1305test.dir/build
.PHONY : poly1305test/fast

#=============================================================================
# Target rules for targets named destest

# Build rule for target.
destest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 destest
.PHONY : destest

# fast build rule for target.
destest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/destest.dir/build.make extern/libressl/tests/CMakeFiles/destest.dir/build
.PHONY : destest/fast

#=============================================================================
# Target rules for targets named asn1evp

# Build rule for target.
asn1evp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asn1evp
.PHONY : asn1evp

# fast build rule for target.
asn1evp/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/asn1evp.dir/build.make extern/libressl/tests/CMakeFiles/asn1evp.dir/build
.PHONY : asn1evp/fast

#=============================================================================
# Target rules for targets named bntest

# Build rule for target.
bntest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bntest
.PHONY : bntest

# fast build rule for target.
bntest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/bntest.dir/build.make extern/libressl/tests/CMakeFiles/bntest.dir/build
.PHONY : bntest/fast

#=============================================================================
# Target rules for targets named cipherstest

# Build rule for target.
cipherstest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cipherstest
.PHONY : cipherstest

# fast build rule for target.
cipherstest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/cipherstest.dir/build.make extern/libressl/tests/CMakeFiles/cipherstest.dir/build
.PHONY : cipherstest/fast

#=============================================================================
# Target rules for targets named tlstest

# Build rule for target.
tlstest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tlstest
.PHONY : tlstest

# fast build rule for target.
tlstest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/tlstest.dir/build.make extern/libressl/tests/CMakeFiles/tlstest.dir/build
.PHONY : tlstest/fast

#=============================================================================
# Target rules for targets named cts128test

# Build rule for target.
cts128test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cts128test
.PHONY : cts128test

# fast build rule for target.
cts128test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/cts128test.dir/build.make extern/libressl/tests/CMakeFiles/cts128test.dir/build
.PHONY : cts128test/fast

#=============================================================================
# Target rules for targets named sha256test

# Build rule for target.
sha256test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sha256test
.PHONY : sha256test

# fast build rule for target.
sha256test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/sha256test.dir/build.make extern/libressl/tests/CMakeFiles/sha256test.dir/build
.PHONY : sha256test/fast

#=============================================================================
# Target rules for targets named casttest

# Build rule for target.
casttest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 casttest
.PHONY : casttest

# fast build rule for target.
casttest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/casttest.dir/build.make extern/libressl/tests/CMakeFiles/casttest.dir/build
.PHONY : casttest/fast

#=============================================================================
# Target rules for targets named valid_handshakes_terminate

# Build rule for target.
valid_handshakes_terminate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 valid_handshakes_terminate
.PHONY : valid_handshakes_terminate

# fast build rule for target.
valid_handshakes_terminate/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/valid_handshakes_terminate.dir/build.make extern/libressl/tests/CMakeFiles/valid_handshakes_terminate.dir/build
.PHONY : valid_handshakes_terminate/fast

#=============================================================================
# Target rules for targets named rsa_test

# Build rule for target.
rsa_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rsa_test
.PHONY : rsa_test

# fast build rule for target.
rsa_test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/rsa_test.dir/build.make extern/libressl/tests/CMakeFiles/rsa_test.dir/build
.PHONY : rsa_test/fast

#=============================================================================
# Target rules for targets named pkcs7test

# Build rule for target.
pkcs7test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pkcs7test
.PHONY : pkcs7test

# fast build rule for target.
pkcs7test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/pkcs7test.dir/build.make extern/libressl/tests/CMakeFiles/pkcs7test.dir/build
.PHONY : pkcs7test/fast

#=============================================================================
# Target rules for targets named gost2814789t

# Build rule for target.
gost2814789t: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gost2814789t
.PHONY : gost2814789t

# fast build rule for target.
gost2814789t/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/gost2814789t.dir/build.make extern/libressl/tests/CMakeFiles/gost2814789t.dir/build
.PHONY : gost2814789t/fast

#=============================================================================
# Target rules for targets named cmstest

# Build rule for target.
cmstest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmstest
.PHONY : cmstest

# fast build rule for target.
cmstest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/cmstest.dir/build.make extern/libressl/tests/CMakeFiles/cmstest.dir/build
.PHONY : cmstest/fast

#=============================================================================
# Target rules for targets named bn_rand_interval

# Build rule for target.
bn_rand_interval: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_rand_interval
.PHONY : bn_rand_interval

# fast build rule for target.
bn_rand_interval/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/bn_rand_interval.dir/build.make extern/libressl/tests/CMakeFiles/bn_rand_interval.dir/build
.PHONY : bn_rand_interval/fast

#=============================================================================
# Target rules for targets named igetest

# Build rule for target.
igetest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igetest
.PHONY : igetest

# fast build rule for target.
igetest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/igetest.dir/build.make extern/libressl/tests/CMakeFiles/igetest.dir/build
.PHONY : igetest/fast

#=============================================================================
# Target rules for targets named recordtest

# Build rule for target.
recordtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 recordtest
.PHONY : recordtest

# fast build rule for target.
recordtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/recordtest.dir/build.make extern/libressl/tests/CMakeFiles/recordtest.dir/build
.PHONY : recordtest/fast

#=============================================================================
# Target rules for targets named cipher_list

# Build rule for target.
cipher_list: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cipher_list
.PHONY : cipher_list

# fast build rule for target.
cipher_list/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/cipher_list.dir/build.make extern/libressl/tests/CMakeFiles/cipher_list.dir/build
.PHONY : cipher_list/fast

#=============================================================================
# Target rules for targets named verifytest

# Build rule for target.
verifytest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verifytest
.PHONY : verifytest

# fast build rule for target.
verifytest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/verifytest.dir/build.make extern/libressl/tests/CMakeFiles/verifytest.dir/build
.PHONY : verifytest/fast

#=============================================================================
# Target rules for targets named bytestringtest

# Build rule for target.
bytestringtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bytestringtest
.PHONY : bytestringtest

# fast build rule for target.
bytestringtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/bytestringtest.dir/build.make extern/libressl/tests/CMakeFiles/bytestringtest.dir/build
.PHONY : bytestringtest/fast

#=============================================================================
# Target rules for targets named ideatest

# Build rule for target.
ideatest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ideatest
.PHONY : ideatest

# fast build rule for target.
ideatest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/ideatest.dir/build.make extern/libressl/tests/CMakeFiles/ideatest.dir/build
.PHONY : ideatest/fast

#=============================================================================
# Target rules for targets named md5test

# Build rule for target.
md5test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md5test
.PHONY : md5test

# fast build rule for target.
md5test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/md5test.dir/build.make extern/libressl/tests/CMakeFiles/md5test.dir/build
.PHONY : md5test/fast

#=============================================================================
# Target rules for targets named timingsafe

# Build rule for target.
timingsafe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timingsafe
.PHONY : timingsafe

# fast build rule for target.
timingsafe/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/timingsafe.dir/build.make extern/libressl/tests/CMakeFiles/timingsafe.dir/build
.PHONY : timingsafe/fast

#=============================================================================
# Target rules for targets named asn1test

# Build rule for target.
asn1test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asn1test
.PHONY : asn1test

# fast build rule for target.
asn1test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/asn1test.dir/build.make extern/libressl/tests/CMakeFiles/asn1test.dir/build
.PHONY : asn1test/fast

#=============================================================================
# Target rules for targets named randtest

# Build rule for target.
randtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 randtest
.PHONY : randtest

# fast build rule for target.
randtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/randtest.dir/build.make extern/libressl/tests/CMakeFiles/randtest.dir/build
.PHONY : randtest/fast

#=============================================================================
# Target rules for targets named arc4randomforktest

# Build rule for target.
arc4randomforktest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arc4randomforktest
.PHONY : arc4randomforktest

# fast build rule for target.
arc4randomforktest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/arc4randomforktest.dir/build.make extern/libressl/tests/CMakeFiles/arc4randomforktest.dir/build
.PHONY : arc4randomforktest/fast

#=============================================================================
# Target rules for targets named aeadtest

# Build rule for target.
aeadtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aeadtest
.PHONY : aeadtest

# fast build rule for target.
aeadtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/aeadtest.dir/build.make extern/libressl/tests/CMakeFiles/aeadtest.dir/build
.PHONY : aeadtest/fast

#=============================================================================
# Target rules for targets named asn1time

# Build rule for target.
asn1time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asn1time
.PHONY : asn1time

# fast build rule for target.
asn1time/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/asn1time.dir/build.make extern/libressl/tests/CMakeFiles/asn1time.dir/build
.PHONY : asn1time/fast

#=============================================================================
# Target rules for targets named evptest

# Build rule for target.
evptest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evptest
.PHONY : evptest

# fast build rule for target.
evptest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/evptest.dir/build.make extern/libressl/tests/CMakeFiles/evptest.dir/build
.PHONY : evptest/fast

#=============================================================================
# Target rules for targets named base64test

# Build rule for target.
base64test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 base64test
.PHONY : base64test

# fast build rule for target.
base64test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/base64test.dir/build.make extern/libressl/tests/CMakeFiles/base64test.dir/build
.PHONY : base64test/fast

#=============================================================================
# Target rules for targets named buffertest

# Build rule for target.
buffertest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 buffertest
.PHONY : buffertest

# fast build rule for target.
buffertest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/buffertest.dir/build.make extern/libressl/tests/CMakeFiles/buffertest.dir/build
.PHONY : buffertest/fast

#=============================================================================
# Target rules for targets named gcm128test

# Build rule for target.
gcm128test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gcm128test
.PHONY : gcm128test

# fast build rule for target.
gcm128test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/gcm128test.dir/build.make extern/libressl/tests/CMakeFiles/gcm128test.dir/build
.PHONY : gcm128test/fast

#=============================================================================
# Target rules for targets named aes_wrap

# Build rule for target.
aes_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aes_wrap
.PHONY : aes_wrap

# fast build rule for target.
aes_wrap/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/aes_wrap.dir/build.make extern/libressl/tests/CMakeFiles/aes_wrap.dir/build
.PHONY : aes_wrap/fast

#=============================================================================
# Target rules for targets named chachatest

# Build rule for target.
chachatest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chachatest
.PHONY : chachatest

# fast build rule for target.
chachatest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/chachatest.dir/build.make extern/libressl/tests/CMakeFiles/chachatest.dir/build
.PHONY : chachatest/fast

#=============================================================================
# Target rules for targets named dsatest

# Build rule for target.
dsatest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsatest
.PHONY : dsatest

# fast build rule for target.
dsatest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/dsatest.dir/build.make extern/libressl/tests/CMakeFiles/dsatest.dir/build
.PHONY : dsatest/fast

#=============================================================================
# Target rules for targets named freenull

# Build rule for target.
freenull: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freenull
.PHONY : freenull

# fast build rule for target.
freenull/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/freenull.dir/build.make extern/libressl/tests/CMakeFiles/freenull.dir/build
.PHONY : freenull/fast

#=============================================================================
# Target rules for targets named rc4test

# Build rule for target.
rc4test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rc4test
.PHONY : rc4test

# fast build rule for target.
rc4test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/rc4test.dir/build.make extern/libressl/tests/CMakeFiles/rc4test.dir/build
.PHONY : rc4test/fast

#=============================================================================
# Target rules for targets named bnaddsub

# Build rule for target.
bnaddsub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bnaddsub
.PHONY : bnaddsub

# fast build rule for target.
bnaddsub/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/bnaddsub.dir/build.make extern/libressl/tests/CMakeFiles/bnaddsub.dir/build
.PHONY : bnaddsub/fast

#=============================================================================
# Target rules for targets named keypairtest

# Build rule for target.
keypairtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 keypairtest
.PHONY : keypairtest

# fast build rule for target.
keypairtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/keypairtest.dir/build.make extern/libressl/tests/CMakeFiles/keypairtest.dir/build
.PHONY : keypairtest/fast

#=============================================================================
# Target rules for targets named bn_to_string

# Build rule for target.
bn_to_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_to_string
.PHONY : bn_to_string

# fast build rule for target.
bn_to_string/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/bn_to_string.dir/build.make extern/libressl/tests/CMakeFiles/bn_to_string.dir/build
.PHONY : bn_to_string/fast

#=============================================================================
# Target rules for targets named mont

# Build rule for target.
mont: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mont
.PHONY : mont

# fast build rule for target.
mont/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/mont.dir/build.make extern/libressl/tests/CMakeFiles/mont.dir/build
.PHONY : mont/fast

#=============================================================================
# Target rules for targets named dhtest

# Build rule for target.
dhtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dhtest
.PHONY : dhtest

# fast build rule for target.
dhtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/dhtest.dir/build.make extern/libressl/tests/CMakeFiles/dhtest.dir/build
.PHONY : dhtest/fast

#=============================================================================
# Target rules for targets named ecdsatest

# Build rule for target.
ecdsatest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecdsatest
.PHONY : ecdsatest

# fast build rule for target.
ecdsatest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/ecdsatest.dir/build.make extern/libressl/tests/CMakeFiles/ecdsatest.dir/build
.PHONY : ecdsatest/fast

#=============================================================================
# Target rules for targets named ectest

# Build rule for target.
ectest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ectest
.PHONY : ectest

# fast build rule for target.
ectest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/ectest.dir/build.make extern/libressl/tests/CMakeFiles/ectest.dir/build
.PHONY : ectest/fast

#=============================================================================
# Target rules for targets named tlsexttest

# Build rule for target.
tlsexttest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tlsexttest
.PHONY : tlsexttest

# fast build rule for target.
tlsexttest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/tlsexttest.dir/build.make extern/libressl/tests/CMakeFiles/tlsexttest.dir/build
.PHONY : tlsexttest/fast

#=============================================================================
# Target rules for targets named hkdf_test

# Build rule for target.
hkdf_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hkdf_test
.PHONY : hkdf_test

# fast build rule for target.
hkdf_test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/hkdf_test.dir/build.make extern/libressl/tests/CMakeFiles/hkdf_test.dir/build
.PHONY : hkdf_test/fast

#=============================================================================
# Target rules for targets named configtest

# Build rule for target.
configtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 configtest
.PHONY : configtest

# fast build rule for target.
configtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/configtest.dir/build.make extern/libressl/tests/CMakeFiles/configtest.dir/build
.PHONY : configtest/fast

#=============================================================================
# Target rules for targets named ecdhtest

# Build rule for target.
ecdhtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecdhtest
.PHONY : ecdhtest

# fast build rule for target.
ecdhtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/ecdhtest.dir/build.make extern/libressl/tests/CMakeFiles/ecdhtest.dir/build
.PHONY : ecdhtest/fast

#=============================================================================
# Target rules for targets named enginetest

# Build rule for target.
enginetest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enginetest
.PHONY : enginetest

# fast build rule for target.
enginetest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/enginetest.dir/build.make extern/libressl/tests/CMakeFiles/enginetest.dir/build
.PHONY : enginetest/fast

#=============================================================================
# Target rules for targets named explicit_bzero

# Build rule for target.
explicit_bzero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 explicit_bzero
.PHONY : explicit_bzero

# fast build rule for target.
explicit_bzero/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/explicit_bzero.dir/build.make extern/libressl/tests/CMakeFiles/explicit_bzero.dir/build
.PHONY : explicit_bzero/fast

#=============================================================================
# Target rules for targets named handshake_table

# Build rule for target.
handshake_table: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handshake_table
.PHONY : handshake_table

# fast build rule for target.
handshake_table/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/handshake_table.dir/build.make extern/libressl/tests/CMakeFiles/handshake_table.dir/build
.PHONY : handshake_table/fast

#=============================================================================
# Target rules for targets named exptest

# Build rule for target.
exptest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exptest
.PHONY : exptest

# fast build rule for target.
exptest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/exptest.dir/build.make extern/libressl/tests/CMakeFiles/exptest.dir/build
.PHONY : exptest/fast

#=============================================================================
# Target rules for targets named key_schedule

# Build rule for target.
key_schedule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 key_schedule
.PHONY : key_schedule

# fast build rule for target.
key_schedule/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/key_schedule.dir/build.make extern/libressl/tests/CMakeFiles/key_schedule.dir/build
.PHONY : key_schedule/fast

#=============================================================================
# Target rules for targets named md4test

# Build rule for target.
md4test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md4test
.PHONY : md4test

# fast build rule for target.
md4test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/md4test.dir/build.make extern/libressl/tests/CMakeFiles/md4test.dir/build
.PHONY : md4test/fast

#=============================================================================
# Target rules for targets named utf8test

# Build rule for target.
utf8test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utf8test
.PHONY : utf8test

# fast build rule for target.
utf8test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/utf8test.dir/build.make extern/libressl/tests/CMakeFiles/utf8test.dir/build
.PHONY : utf8test/fast

#=============================================================================
# Target rules for targets named bftest

# Build rule for target.
bftest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bftest
.PHONY : bftest

# fast build rule for target.
bftest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/bftest.dir/build.make extern/libressl/tests/CMakeFiles/bftest.dir/build
.PHONY : bftest/fast

#=============================================================================
# Target rules for targets named optionstest

# Build rule for target.
optionstest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 optionstest
.PHONY : optionstest

# fast build rule for target.
optionstest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/optionstest.dir/build.make extern/libressl/tests/CMakeFiles/optionstest.dir/build
.PHONY : optionstest/fast

#=============================================================================
# Target rules for targets named pq_test

# Build rule for target.
pq_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pq_test
.PHONY : pq_test

# fast build rule for target.
pq_test/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/pq_test.dir/build.make extern/libressl/tests/CMakeFiles/pq_test.dir/build
.PHONY : pq_test/fast

#=============================================================================
# Target rules for targets named hmactest

# Build rule for target.
hmactest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hmactest
.PHONY : hmactest

# fast build rule for target.
hmactest/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/hmactest.dir/build.make extern/libressl/tests/CMakeFiles/hmactest.dir/build
.PHONY : hmactest/fast

#=============================================================================
# Target rules for targets named pbkdf2

# Build rule for target.
pbkdf2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pbkdf2
.PHONY : pbkdf2

# fast build rule for target.
pbkdf2/fast:
	$(MAKE) $(MAKESILENT) -f extern/libressl/tests/CMakeFiles/pbkdf2.dir/build.make extern/libressl/tests/CMakeFiles/pbkdf2.dir/build
.PHONY : pbkdf2/fast

src/client/client.o: src/client/client.c.o

.PHONY : src/client/client.o

# target to build an object file
src/client/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.c.o
.PHONY : src/client/client.c.o

src/client/client.i: src/client/client.c.i

.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.c.i
.PHONY : src/client/client.c.i

src/client/client.s: src/client/client.c.s

.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.c.s
.PHONY : src/client/client.c.s

src/server/server.o: src/server/server.c.o

.PHONY : src/server/server.o

# target to build an object file
src/server/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.o
.PHONY : src/server/server.c.o

src/server/server.i: src/server/server.c.i

.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.i
.PHONY : src/server/server.c.i

src/server/server.s: src/server/server.c.s

.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.s
.PHONY : src/server/server.c.s

src/server/strlcpy.o: src/server/strlcpy.c.o

.PHONY : src/server/strlcpy.o

# target to build an object file
src/server/strlcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/strlcpy.c.o
.PHONY : src/server/strlcpy.c.o

src/server/strlcpy.i: src/server/strlcpy.c.i

.PHONY : src/server/strlcpy.i

# target to preprocess a source file
src/server/strlcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/strlcpy.c.i
.PHONY : src/server/strlcpy.c.i

src/server/strlcpy.s: src/server/strlcpy.c.s

.PHONY : src/server/strlcpy.s

# target to generate assembly for a file
src/server/strlcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/strlcpy.c.s
.PHONY : src/server/strlcpy.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... aeadtest"
	@echo "... aes_wrap"
	@echo "... arc4randomforktest"
	@echo "... asn1evp"
	@echo "... asn1test"
	@echo "... asn1time"
	@echo "... base64test"
	@echo "... bftest"
	@echo "... bn_rand_interval"
	@echo "... bn_to_string"
	@echo "... bnaddsub"
	@echo "... bntest"
	@echo "... buffertest"
	@echo "... bytestringtest"
	@echo "... casttest"
	@echo "... chachatest"
	@echo "... cipher_list"
	@echo "... cipherstest"
	@echo "... client"
	@echo "... cmstest"
	@echo "... configtest"
	@echo "... crypto"
	@echo "... cts128test"
	@echo "... destest"
	@echo "... dhtest"
	@echo "... dsatest"
	@echo "... ecdhtest"
	@echo "... ecdsatest"
	@echo "... ectest"
	@echo "... enginetest"
	@echo "... evptest"
	@echo "... explicit_bzero"
	@echo "... exptest"
	@echo "... freenull"
	@echo "... gcm128test"
	@echo "... gost2814789t"
	@echo "... handshake_table"
	@echo "... hkdf_test"
	@echo "... hmactest"
	@echo "... ideatest"
	@echo "... igetest"
	@echo "... key_schedule"
	@echo "... keypairtest"
	@echo "... md4test"
	@echo "... md5test"
	@echo "... mont"
	@echo "... nc"
	@echo "... ocspcheck"
	@echo "... openssl"
	@echo "... optionstest"
	@echo "... pbkdf2"
	@echo "... pkcs7test"
	@echo "... poly1305test"
	@echo "... pq_test"
	@echo "... randtest"
	@echo "... rc2test"
	@echo "... rc4test"
	@echo "... record_layer_test"
	@echo "... recordtest"
	@echo "... rfc5280time"
	@echo "... rmdtest"
	@echo "... rsa_test"
	@echo "... server"
	@echo "... servertest"
	@echo "... sha1test"
	@echo "... sha256test"
	@echo "... sha512test"
	@echo "... sm3test"
	@echo "... sm4test"
	@echo "... ssl"
	@echo "... ssl_versions"
	@echo "... ssltest"
	@echo "... timingsafe"
	@echo "... tls"
	@echo "... tls_ext_alpn"
	@echo "... tls_prf"
	@echo "... tlsexttest"
	@echo "... tlstest"
	@echo "... utf8test"
	@echo "... valid_handshakes_terminate"
	@echo "... verifytest"
	@echo "... x25519test"
	@echo "... x509name"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/server/strlcpy.o"
	@echo "... src/server/strlcpy.i"
	@echo "... src/server/strlcpy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

